# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kredyty.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kredyty(object):
    def setupUi(self, Kredyty):
        Kredyty.setObjectName("Kredyty")
        Kredyty.resize(326, 152)
        self.verticalLayout = QtWidgets.QVBoxLayout(Kredyty)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Kredyty)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Kredyty)
        QtCore.QMetaObject.connectSlotsByName(Kredyty)

    def retranslateUi(self, Kredyty):
        _translate = QtCore.QCoreApplication.translate
        Kredyty.setWindowTitle(_translate("Kredyty", "Form"))
