#############################################################################
# Makefile for building: FullScreanApp
# Generated by qmake (2.01a) (Qt 4.8.7) on: niedz. pa? 16 09:41:06 2022
# Project:  FullScreanApp.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -o Makefile FullScreanApp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		blackwidget.cpp \
		rssitem.cpp \
		zegar.cpp \
		analogclock.cpp moc_mainwindow.cpp \
		moc_blackwidget.cpp \
		moc_zegar.cpp \
		qrc_ikony.cpp
OBJECTS       = main.o \
		mainwindow.o \
		blackwidget.o \
		rssitem.o \
		zegar.o \
		analogclock.o \
		moc_mainwindow.o \
		moc_blackwidget.o \
		moc_zegar.o \
		qrc_ikony.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FullScreanApp.pro
QMAKE_TARGET  = FullScreanApp
DESTDIR       = 
TARGET        = FullScreanApp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_zegar.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FullScreanApp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile FullScreanApp.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile FullScreanApp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FullScreanApp1.0.0 || $(MKDIR) .tmp/FullScreanApp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FullScreanApp1.0.0/ && $(COPY_FILE) --parents mainwindow.h blackwidget.h rssitem.h zegar.h analogclock.h .tmp/FullScreanApp1.0.0/ && $(COPY_FILE) --parents ikony.qrc .tmp/FullScreanApp1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp blackwidget.cpp rssitem.cpp zegar.cpp analogclock.cpp .tmp/FullScreanApp1.0.0/ && $(COPY_FILE) --parents zegar.ui .tmp/FullScreanApp1.0.0/ && (cd `dirname .tmp/FullScreanApp1.0.0` && $(TAR) FullScreanApp1.0.0.tar FullScreanApp1.0.0 && $(COMPRESS) FullScreanApp1.0.0.tar) && $(MOVE) `dirname .tmp/FullScreanApp1.0.0`/FullScreanApp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FullScreanApp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_blackwidget.cpp moc_zegar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_blackwidget.cpp moc_zegar.cpp
moc_mainwindow.cpp: analogclock.h \
		blackwidget.h \
		zegar.h \
		mainwindow.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_blackwidget.cpp: blackwidget.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) blackwidget.h -o moc_blackwidget.cpp

moc_zegar.cpp: blackwidget.h \
		zegar.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) zegar.h -o moc_zegar.cpp

compiler_rcc_make_all: qrc_ikony.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ikony.cpp
qrc_ikony.cpp: ikony.qrc \
		moon.png \
		sun.png \
		analog.png
	/usr/lib/arm-linux-gnueabihf/qt4/bin/rcc -name ikony ikony.qrc -o qrc_ikony.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_zegar.h
compiler_uic_clean:
	-$(DEL_FILE) ui_zegar.h
ui_zegar.h: zegar.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic zegar.ui -o ui_zegar.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		analogclock.h \
		blackwidget.h \
		zegar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		analogclock.h \
		blackwidget.h \
		zegar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

blackwidget.o: blackwidget.cpp blackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackwidget.o blackwidget.cpp

rssitem.o: rssitem.cpp rssitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rssitem.o rssitem.cpp

zegar.o: zegar.cpp zegar.h \
		blackwidget.h \
		ui_zegar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zegar.o zegar.cpp

analogclock.o: analogclock.cpp analogclock.h \
		blackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analogclock.o analogclock.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_blackwidget.o: moc_blackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blackwidget.o moc_blackwidget.cpp

moc_zegar.o: moc_zegar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zegar.o moc_zegar.cpp

qrc_ikony.o: qrc_ikony.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ikony.o qrc_ikony.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

