#############################################################################
# Makefile for building: FullScreanApp
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  FullScreanApp.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile FullScreanApp.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Iqjson4 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FullScreanApp1.0.0
DISTDIR = /home/marcin/development/qt/fullscreanApp/.tmp/FullScreanApp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qjson4/QJsonArray.cpp \
		qjson4/QJsonDocument.cpp \
		qjson4/QJsonObject.cpp \
		qjson4/QJsonParseError.cpp \
		qjson4/QJsonValue.cpp \
		qjson4/QJsonValueRef.cpp \
		qjson4/QJsonParser.cpp \
		main.cpp \
		mainwindow.cpp \
		blackwidget.cpp \
		rssitem.cpp \
		zegar.cpp \
		analogclock.cpp \
		ip.cpp \
		pogoda.cpp \
		informacje.cpp qrc_ikony.cpp \
		moc_mainwindow.cpp \
		moc_blackwidget.cpp \
		moc_zegar.cpp \
		moc_ip.cpp \
		moc_pogoda.cpp \
		moc_informacje.cpp
OBJECTS       = QJsonArray.o \
		QJsonDocument.o \
		QJsonObject.o \
		QJsonParseError.o \
		QJsonValue.o \
		QJsonValueRef.o \
		QJsonParser.o \
		main.o \
		mainwindow.o \
		blackwidget.o \
		rssitem.o \
		zegar.o \
		analogclock.o \
		ip.o \
		pogoda.o \
		informacje.o \
		qrc_ikony.o \
		moc_mainwindow.o \
		moc_blackwidget.o \
		moc_zegar.o \
		moc_ip.o \
		moc_pogoda.o \
		moc_informacje.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		qjson4/QJson4.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FullScreanApp.pro qjson4/QJsonArray.h \
		qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonParseError.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonParser.h \
		qjson4/QJsonRoot.h \
		mainwindow.h \
		blackwidget.h \
		rssitem.h \
		zegar.h \
		analogclock.h \
		ip.h \
		pogoda.h \
		informacje.h qjson4/QJsonArray.cpp \
		qjson4/QJsonDocument.cpp \
		qjson4/QJsonObject.cpp \
		qjson4/QJsonParseError.cpp \
		qjson4/QJsonValue.cpp \
		qjson4/QJsonValueRef.cpp \
		qjson4/QJsonParser.cpp \
		main.cpp \
		mainwindow.cpp \
		blackwidget.cpp \
		rssitem.cpp \
		zegar.cpp \
		analogclock.cpp \
		ip.cpp \
		pogoda.cpp \
		informacje.cpp
QMAKE_TARGET  = FullScreanApp
DESTDIR       = 
TARGET        = FullScreanApp


first: all
####### Build rules

FullScreanApp: ui_zegar.h ui_ip.h ui_pogoda.h ui_informacje.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FullScreanApp.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		qjson4/QJson4.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FullScreanApp.pro \
		ikony.qrc
	$(QMAKE) -o Makefile FullScreanApp.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
qjson4/QJson4.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
FullScreanApp.pro:
ikony.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile FullScreanApp.pro

qmake_all: FORCE


all: Makefile FullScreanApp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ikony.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qjson4/QJsonArray.h qjson4/QJsonDocument.h qjson4/QJsonObject.h qjson4/QJsonParseError.h qjson4/QJsonValue.h qjson4/QJsonValueRef.h qjson4/QJsonParser.h qjson4/QJsonRoot.h mainwindow.h blackwidget.h rssitem.h zegar.h analogclock.h ip.h pogoda.h informacje.h $(DISTDIR)/
	$(COPY_FILE) --parents qjson4/QJsonArray.cpp qjson4/QJsonDocument.cpp qjson4/QJsonObject.cpp qjson4/QJsonParseError.cpp qjson4/QJsonValue.cpp qjson4/QJsonValueRef.cpp qjson4/QJsonParser.cpp main.cpp mainwindow.cpp blackwidget.cpp rssitem.cpp zegar.cpp analogclock.cpp ip.cpp pogoda.cpp informacje.cpp $(DISTDIR)/
	$(COPY_FILE) --parents zegar.ui ip.ui pogoda.ui informacje.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_ikony.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ikony.cpp
qrc_ikony.cpp: ikony.qrc \
		/usr/lib/qt5/bin/rcc \
		img/wi-wind-beaufort-6.svg \
		img/wi-moon-first-quarter.svg \
		img/wi-refresh.svg \
		img/wi-day-cloudy-windy.svg \
		img/wi-wind-beaufort-12.svg \
		img/wi-moon-alt-waning-crescent-3.svg \
		img/wi-moon-alt-new.svg \
		img/wi-time-6.svg \
		img/wi-wind-beaufort-4.svg \
		img/wi-moon-alt-first-quarter.svg \
		img/wi-alien.svg \
		img/wi-night-alt-sprinkle.svg \
		img/wi-wind-beaufort-10.svg \
		img/wi-day-sprinkle.svg \
		img/wi-moon-alt-waning-crescent-1.svg \
		img/wi-night-fog.svg \
		img/wi-sunrise.svg \
		img/wi-night-partly-cloudy.svg \
		img/wi-night-alt-cloudy-gusts.svg \
		img/wi-raindrops.svg \
		img/wi-moon-alt-full.svg \
		img/wi-day-haze.svg \
		img/wi-night-rain-mix.svg \
		img/wi-lunar-eclipse.svg \
		img/wi-time-4.svg \
		img/wi-night-alt-snow-wind.svg \
		img/wi-night-rain-wind.svg \
		img/wi-wind-beaufort-2.svg \
		img/wi-direction-left.svg \
		img/wi-day-sunny-overcast.svg \
		img/wi-moon-alt-waxing-gibbous-6.svg \
		img/wi-cloud-up.svg \
		img/wi-na.svg \
		img/wi-fire.svg \
		img/wi-day-snow-wind.svg \
		img/wi-moon-new.svg \
		img/wi-day-windy.svg \
		img/wi-celsius.svg \
		img/wi-direction-up.svg \
		img/wi-moon-waxing-gibbous-6.svg \
		img/wi-time-2.svg \
		img/wi-train.svg \
		img/wi-day-storm-showers.svg \
		img/wi-moon-waxing-crescent-4.svg \
		img/wi-wind-beaufort-0.svg \
		img/wi-direction-down.svg \
		img/wi-night-rain.svg \
		img/wi-moon-alt-waxing-gibbous-4.svg \
		img/wi-night-alt-rain-mix.svg \
		img/wi-day-rain-mix.svg \
		img/wi-thermometer-exterior.svg \
		img/wi-thermometer-internal.svg \
		img/wi-sandstorm.svg \
		img/wi-moon-third-quarter.svg \
		img/wi-showers.svg \
		img/wi-night-alt-sleet.svg \
		img/wi-night-alt-sleet-storm.svg \
		img/wi-moon-waxing-gibbous-4.svg \
		img/wi-night-alt-storm-showers.svg \
		img/wi-moon-waxing-crescent-2.svg \
		img/wi-moon-alt-waxing-gibbous-2.svg \
		img/wi-moon-alt-waning-gibbous-5.svg \
		img/wi-day-light-wind.svg \
		img/wi-day-cloudy-gusts.svg \
		img/wi-night-cloudy-high.svg \
		img/wi-moon-alt-waxing-crescent-5.svg \
		img/wi-night-alt-showers.svg \
		img/wi-thunderstorm.svg \
		img/wi-day-hail.svg \
		img/wi-hot.svg \
		img/wi-night-lightning.svg \
		img/wi-moon-alt-third-quarter.svg \
		img/wi-storm-warning.svg \
		img/wi-moon-waxing-gibbous-2.svg \
		img/wi-direction-up-left.svg \
		img/wi-moon-waning-gibbous-5.svg \
		img/wi-night-alt-rain.svg \
		img/wi-moon-waning-crescent-5.svg \
		img/wi-storm-showers.svg \
		img/wi-moon-full.svg \
		img/wi-time-11.svg \
		img/wi-moon-alt-waning-gibbous-3.svg \
		img/wi-day-sleet.svg \
		img/wi-cloudy-windy.svg \
		img/wi-moon-alt-waxing-crescent-3.svg \
		img/wi-day-fog.svg \
		img/wi-cloud-down.svg \
		img/wi-moon-waning-crescent-3.svg \
		img/wi-moon-waning-gibbous-3.svg \
		img/wi-moon-waxing-6.svg \
		img/wi-rain.svg \
		img/wi-sprinkle.svg \
		img/wi-wind-beaufort-9.svg \
		img/wi-moon-alt-waning-gibbous-1.svg \
		img/wi-moon-alt-waning-crescent-6.svg \
		img/wi-moon-alt-waxing-crescent-1.svg \
		img/wi-moon-waning-gibbous-1.svg \
		img/wi-moon-waning-crescent-1.svg \
		img/wi-day-snow.svg \
		img/wi-time-9.svg \
		img/wi-wind-beaufort-7.svg \
		img/wi-meteor.svg \
		img/wi-direction-down-right.svg \
		img/wi-moon-alt-waning-crescent-4.svg \
		img/wi-barometer.svg \
		img/wi-direction-up-right.svg \
		img/wi-rain-wind.svg \
		img/wi-windy.svg \
		img/wi-night-alt-partly-cloudy.svg \
		img/wi-day-sleet-storm.svg \
		img/wi-day-cloudy.svg \
		img/wi-time-7.svg \
		img/wi-moonrise.svg \
		img/wi-wind-beaufort-5.svg \
		img/wi-umbrella.svg \
		img/wi-rain-mix.svg \
		img/wi-wind-beaufort-11.svg \
		img/wi-day-showers.svg \
		img/wi-moon-alt-waning-crescent-2.svg \
		img/wi-night-snow-wind.svg \
		img/wi-raindrop.svg \
		img/wi-tornado.svg \
		img/wi-night-hail.svg \
		img/wi-night-sleet.svg \
		img/wi-strong-wind.svg \
		img/wi-night-alt-cloudy-high.svg \
		img/wi-time-5.svg \
		img/wi-snowflake-cold.svg \
		img/wi-wind-beaufort-3.svg \
		img/wi-night-clear.svg \
		img/wi-degrees.svg \
		img/wi-night-alt-cloudy.svg \
		img/wi-cloudy-gusts.svg \
		img/wi-night-snow-thunderstorm.svg \
		img/wi-wind-deg.svg \
		img/wi-volcano.svg \
		img/wi-time-3.svg \
		img/wi-moon-waxing-crescent-5.svg \
		img/wi-wind-beaufort-1.svg \
		img/wi-lightning.svg \
		img/wi-solar-eclipse.svg \
		img/wi-night-thunderstorm.svg \
		img/wi-sleet.svg \
		img/wi-moon-alt-waxing-gibbous-5.svg \
		img/wi-hurricane-warning.svg \
		img/wi-night-alt-hail.svg \
		img/wi-cloud-refresh.svg \
		img/wi-night-alt-rain-wind.svg \
		img/wi-night-cloudy-windy.svg \
		img/wi-moon-waxing-gibbous-5.svg \
		img/wi-night-snow.svg \
		img/wi-time-1.svg \
		img/wi-moon-waxing-crescent-3.svg \
		img/wi-day-rain-wind.svg \
		img/wi-smog.svg \
		img/wi-flood.svg \
		img/wi-gale-warning.svg \
		img/wi-moon-alt-waxing-gibbous-3.svg \
		img/wi-moon-alt-waning-gibbous-6.svg \
		img/wi-night-showers.svg \
		img/wi-earthquake.svg \
		img/wi-night-cloudy.svg \
		img/wi-moon-alt-waxing-crescent-6.svg \
		img/wi-refresh-alt.svg \
		img/wi-hail.svg \
		img/wi-moon-waxing-gibbous-3.svg \
		img/wi-night-alt-thunderstorm.svg \
		img/wi-moon-waning-gibbous-6.svg \
		img/wi-moon-waning-crescent-6.svg \
		img/wi-day-snow-thunderstorm.svg \
		img/wi-moon-waxing-crescent-1.svg \
		img/wi-cloudy.svg \
		img/wi-time-12.svg \
		img/wi-fog.svg \
		img/wi-direction-down-left.svg \
		img/wi-moon-alt-waxing-gibbous-1.svg \
		img/wi-moon-alt-waning-gibbous-4.svg \
		img/wi-cloud.svg \
		img/wi-night-alt-cloudy-windy.svg \
		img/wi-moon-alt-waxing-crescent-4.svg \
		img/wi-smoke.svg \
		img/wi-night-alt-snow.svg \
		img/wi-fahrenheit.svg \
		img/wi-day-cloudy-high.svg \
		img/wi-moon-waxing-gibbous-1.svg \
		img/wi-night-storm-showers.svg \
		img/wi-moon-waning-gibbous-4.svg \
		img/wi-moon-waning-crescent-4.svg \
		img/wi-sunset.svg \
		img/wi-direction-right.svg \
		img/wi-thermometer.svg \
		img/wi-tsunami.svg \
		img/wi-time-10.svg \
		img/wi-stars.svg \
		img/wi-dust.svg \
		img/wi-moon-alt-waning-gibbous-2.svg \
		img/wi-small-craft-advisory.svg \
		img/wi-night-alt-lightning.svg \
		img/wi-hurricane.svg \
		img/wi-moon-alt-waxing-crescent-2.svg \
		img/wi-moonset.svg \
		img/wi-day-lightning.svg \
		img/wi-humidity.svg \
		img/wi-day-sunny.svg \
		img/wi-horizon-alt.svg \
		img/wi-snow.svg \
		img/wi-snow-wind.svg \
		img/wi-moon-waning-gibbous-2.svg \
		img/wi-moon-waning-crescent-2.svg \
		img/wi-wind-beaufort-8.svg \
		img/wi-day-rain.svg \
		img/wi-night-alt-snow-thunderstorm.svg \
		img/wi-horizon.svg \
		img/wi-night-sleet-storm.svg \
		img/wi-moon-alt-waning-crescent-5.svg \
		img/wi-night-sprinkle.svg \
		img/wi-day-thunderstorm.svg \
		img/wi-night-cloudy-gusts.svg \
		img/wi-time-8.svg \
		analog.png \
		moon.png \
		sun.png \
		Bez\ nazwy.png \
		weathericons-regular-webfont.ttf \
		fonts/roboto-slab/Roboto-Slab-Bold.ttf \
		fonts/roboto-slab/Roboto-Slab-Thin.ttf \
		fonts/roboto-slab/Roboto-Slab-Regular.ttf \
		fonts/roboto-slab/Roboto-Slab-Light.ttf \
		fonts/robotic/Roboto-BoldItalic.ttf \
		fonts/robotic/Roboto-RegularItalic.ttf \
		fonts/robotic/Roboto-Regular.ttf \
		fonts/robotic/Roboto-ThinItalic.ttf \
		fonts/robotic/Roboto-BlackItalic.ttf \
		fonts/robotic/Roboto-Light.ttf \
		fonts/robotic/Roboto-Medium.ttf \
		fonts/robotic/Roboto-Black.ttf \
		fonts/robotic/Roboto-Bold.ttf \
		fonts/robotic/Roboto-LightItalic.ttf \
		fonts/robotic/Roboto-MediumItalic.ttf \
		fonts/robotic/Roboto-Thin.ttf \
		fonts/roboto-condensed/Roboto-Condensed-Light.ttf \
		fonts/roboto-condensed/Roboto-Condensed-LightItalic.ttf \
		fonts/roboto-condensed/Roboto-Condensed-Regular.ttf \
		fonts/roboto-condensed/Roboto-Condensed-BoldItalic.ttf \
		fonts/roboto-condensed/Roboto-Condensed-RegularItalic.ttf \
		fonts/roboto-condensed/Roboto-Condensed-Bold.ttf
	/usr/lib/qt5/bin/rcc -name ikony ikony.qrc -o qrc_ikony.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_blackwidget.cpp moc_zegar.cpp moc_ip.cpp moc_pogoda.cpp moc_informacje.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_blackwidget.cpp moc_zegar.cpp moc_ip.cpp moc_pogoda.cpp moc_informacje.cpp
moc_mainwindow.cpp: mainwindow.h \
		analogclock.h \
		blackwidget.h \
		zegar.h \
		ip.h \
		informacje.h \
		rssitem.h \
		pogoda.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_blackwidget.cpp: blackwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include blackwidget.h -o moc_blackwidget.cpp

moc_zegar.cpp: zegar.h \
		blackwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include zegar.h -o moc_zegar.cpp

moc_ip.cpp: ip.h \
		blackwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ip.h -o moc_ip.cpp

moc_pogoda.cpp: pogoda.h \
		blackwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pogoda.h -o moc_pogoda.cpp

moc_informacje.cpp: informacje.h \
		blackwidget.h \
		rssitem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/marcin/development/qt/fullscreanApp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp -I/home/marcin/development/qt/fullscreanApp/qjson4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include informacje.h -o moc_informacje.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_zegar.h ui_ip.h ui_pogoda.h ui_informacje.h
compiler_uic_clean:
	-$(DEL_FILE) ui_zegar.h ui_ip.h ui_pogoda.h ui_informacje.h
ui_zegar.h: zegar.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic zegar.ui -o ui_zegar.h

ui_ip.h: ip.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ip.ui -o ui_ip.h

ui_pogoda.h: pogoda.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic pogoda.ui -o ui_pogoda.h

ui_informacje.h: informacje.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic informacje.ui -o ui_informacje.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

QJsonArray.o: qjson4/QJsonArray.cpp qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonArray.o qjson4/QJsonArray.cpp

QJsonDocument.o: qjson4/QJsonDocument.cpp qjson4/QJsonDocument.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonParser.h \
		qjson4/QJsonParseError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonDocument.o qjson4/QJsonDocument.cpp

QJsonObject.o: qjson4/QJsonObject.cpp qjson4/QJsonObject.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonObject.o qjson4/QJsonObject.cpp

QJsonParseError.o: qjson4/QJsonParseError.cpp qjson4/QJsonParseError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonParseError.o qjson4/QJsonParseError.cpp

QJsonValue.o: qjson4/QJsonValue.cpp qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonValueRef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonValue.o qjson4/QJsonValue.cpp

QJsonValueRef.o: qjson4/QJsonValueRef.cpp qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonValueRef.o qjson4/QJsonValueRef.cpp

QJsonParser.o: qjson4/QJsonParser.cpp qjson4/QJsonParser.h \
		qjson4/QJsonParseError.h \
		qjson4/QJsonArray.h \
		qjson4/QJsonRoot.h \
		qjson4/QJsonObject.h \
		qjson4/QJsonValueRef.h \
		qjson4/QJsonValue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QJsonParser.o qjson4/QJsonParser.cpp

main.o: main.cpp mainwindow.h \
		analogclock.h \
		blackwidget.h \
		zegar.h \
		ip.h \
		informacje.h \
		rssitem.h \
		pogoda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		analogclock.h \
		blackwidget.h \
		zegar.h \
		ip.h \
		informacje.h \
		rssitem.h \
		pogoda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

blackwidget.o: blackwidget.cpp blackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackwidget.o blackwidget.cpp

rssitem.o: rssitem.cpp rssitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rssitem.o rssitem.cpp

zegar.o: zegar.cpp zegar.h \
		blackwidget.h \
		ui_zegar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zegar.o zegar.cpp

analogclock.o: analogclock.cpp analogclock.h \
		blackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analogclock.o analogclock.cpp

ip.o: ip.cpp ip.h \
		blackwidget.h \
		ui_ip.h \
		qjson4/QJsonDocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ip.o ip.cpp

pogoda.o: pogoda.cpp pogoda.h \
		blackwidget.h \
		ui_pogoda.h \
		qjson4/QJsonDocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pogoda.o pogoda.cpp

informacje.o: informacje.cpp informacje.h \
		blackwidget.h \
		rssitem.h \
		ui_informacje.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o informacje.o informacje.cpp

qrc_ikony.o: qrc_ikony.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ikony.o qrc_ikony.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_blackwidget.o: moc_blackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blackwidget.o moc_blackwidget.cpp

moc_zegar.o: moc_zegar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zegar.o moc_zegar.cpp

moc_ip.o: moc_ip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ip.o moc_ip.cpp

moc_pogoda.o: moc_pogoda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pogoda.o moc_pogoda.cpp

moc_informacje.o: moc_informacje.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_informacje.o moc_informacje.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

