# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/statystyki.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stats(object):
    def setupUi(self, Stats):
        Stats.setObjectName("Stats")
        Stats.resize(250, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Stats)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cpuBox = QtWidgets.QGroupBox(Stats)
        self.cpuBox.setStyleSheet("border-color: rgb(186, 189, 182);")
        self.cpuBox.setFlat(True)
        self.cpuBox.setObjectName("cpuBox")
        self.formLayoutProcesor = QtWidgets.QFormLayout(self.cpuBox)
        self.formLayoutProcesor.setContentsMargins(0, 0, 0, 0)
        self.formLayoutProcesor.setSpacing(2)
        self.formLayoutProcesor.setObjectName("formLayoutProcesor")
        self.etCpuSpeed = QtWidgets.QLabel(self.cpuBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etCpuSpeed.setFont(font)
        self.etCpuSpeed.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etCpuSpeed.setObjectName("etCpuSpeed")
        self.formLayoutProcesor.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.etCpuSpeed)
        self.label = QtWidgets.QLabel(self.cpuBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.formLayoutProcesor.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cpuUsage = QtWidgets.QLabel(self.cpuBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.cpuUsage.setFont(font)
        self.cpuUsage.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.cpuUsage.setObjectName("cpuUsage")
        self.formLayoutProcesor.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cpuUsage)
        self.cpuSpeed = QtWidgets.QLabel(self.cpuBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.cpuSpeed.setFont(font)
        self.cpuSpeed.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.cpuSpeed.setObjectName("cpuSpeed")
        self.formLayoutProcesor.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cpuSpeed)
        self.verticalLayout.addWidget(self.cpuBox)
        self.tempBox = QtWidgets.QGroupBox(Stats)
        self.tempBox.setObjectName("tempBox")
        self.formLayoutTemp = QtWidgets.QFormLayout(self.tempBox)
        self.formLayoutTemp.setContentsMargins(0, 0, 0, 0)
        self.formLayoutTemp.setSpacing(2)
        self.formLayoutTemp.setObjectName("formLayoutTemp")
        self.etProcesro = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etProcesro.setFont(font)
        self.etProcesro.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etProcesro.setObjectName("etProcesro")
        self.formLayoutTemp.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.etProcesro)
        self.tempGPU = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.tempGPU.setFont(font)
        self.tempGPU.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.tempGPU.setObjectName("tempGPU")
        self.formLayoutTemp.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tempGPU)
        self.etMonitor = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etMonitor.setFont(font)
        self.etMonitor.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etMonitor.setObjectName("etMonitor")
        self.formLayoutTemp.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.etMonitor)
        self.tempMonitor = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.tempMonitor.setFont(font)
        self.tempMonitor.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.tempMonitor.setObjectName("tempMonitor")
        self.formLayoutTemp.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tempMonitor)
        self.etRaspberry = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etRaspberry.setFont(font)
        self.etRaspberry.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etRaspberry.setObjectName("etRaspberry")
        self.formLayoutTemp.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.etRaspberry)
        self.tempRasp = QtWidgets.QLabel(self.tempBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.tempRasp.setFont(font)
        self.tempRasp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.tempRasp.setObjectName("tempRasp")
        self.formLayoutTemp.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tempRasp)
        self.verticalLayout.addWidget(self.tempBox)
        self.ipBox = QtWidgets.QGroupBox(Stats)
        self.ipBox.setObjectName("ipBox")
        self.formLayoutIp = QtWidgets.QFormLayout(self.ipBox)
        self.formLayoutIp.setContentsMargins(0, 0, 0, 0)
        self.formLayoutIp.setSpacing(2)
        self.formLayoutIp.setObjectName("formLayoutIp")
        self.etLocalIp = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etLocalIp.setFont(font)
        self.etLocalIp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etLocalIp.setObjectName("etLocalIp")
        self.formLayoutIp.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.etLocalIp)
        self.localIp = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.localIp.setFont(font)
        self.localIp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.localIp.setObjectName("localIp")
        self.formLayoutIp.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.localIp)
        self.etInternetIp = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etInternetIp.setFont(font)
        self.etInternetIp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etInternetIp.setObjectName("etInternetIp")
        self.formLayoutIp.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.etInternetIp)
        self.zewnetrzneIp = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.zewnetrzneIp.setFont(font)
        self.zewnetrzneIp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.zewnetrzneIp.setObjectName("zewnetrzneIp")
        self.formLayoutIp.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zewnetrzneIp)
        self.etConnected = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.etConnected.setFont(font)
        self.etConnected.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.etConnected.setObjectName("etConnected")
        self.formLayoutIp.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.etConnected)
        self.netstatus = QtWidgets.QLabel(self.ipBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab ExtraLight")
        font.setPointSize(12)
        self.netstatus.setFont(font)
        self.netstatus.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.netstatus.setObjectName("netstatus")
        self.formLayoutIp.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.netstatus)
        self.verticalLayout.addWidget(self.ipBox)

        self.retranslateUi(Stats)
        QtCore.QMetaObject.connectSlotsByName(Stats)

    def retranslateUi(self, Stats):
        _translate = QtCore.QCoreApplication.translate
        Stats.setWindowTitle(_translate("Stats", "Form"))
        self.cpuBox.setTitle(_translate("Stats", "Procesor"))
        self.etCpuSpeed.setText(_translate("Stats", "Prędkość"))
        self.label.setText(_translate("Stats", "Użycie"))
        self.cpuUsage.setText(_translate("Stats", "0 %"))
        self.cpuSpeed.setText(_translate("Stats", "0 MHz"))
        self.tempBox.setTitle(_translate("Stats", "Temperatury"))
        self.etProcesro.setText(_translate("Stats", "Procesor"))
        self.tempGPU.setText(_translate("Stats", "0"))
        self.etMonitor.setText(_translate("Stats", "Monitor"))
        self.tempMonitor.setText(_translate("Stats", "0"))
        self.etRaspberry.setText(_translate("Stats", "Raspberry"))
        self.tempRasp.setText(_translate("Stats", "0"))
        self.ipBox.setTitle(_translate("Stats", "IP"))
        self.etLocalIp.setText(_translate("Stats", "Lokalne"))
        self.localIp.setText(_translate("Stats", "0.0.0.0"))
        self.etInternetIp.setText(_translate("Stats", "Zewnetrzne"))
        self.zewnetrzneIp.setText(_translate("Stats", "0.0.0.0"))
        self.etConnected.setText(_translate("Stats", "Połączenie"))
        self.netstatus.setText(_translate("Stats", "Brak internetu"))

